language: node_js
node_js:
- '8'
cache:
  directories:
  - "$HOME/gcloud/"
env:
- PATH=$PATH:$HOME/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
filter_secrets: false
branches:
  only:
  - master
  - stage
before_install:
- openssl aes-256-cbc -K $encrypted_d88b7c395367_key -iv $encrypted_d88b7c395367_iv
  -in gce-key.json.enc -out gce-key.json -d
- ssh-keygen -q -N "" -f ~/.ssh/google_compute_engine
- if [ ! -d $HOME/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file gce-key.json
- echo "  SQL_DATABASE:" $SQL_DATABASE >> app.yaml
- echo "  SQL_HOST:" $SQL_HOST >> app.yaml
- echo "  SQL_PASSWORD:" $SQL_PASSWORD >> app.yaml
- echo "  SQL_USER:" $SQL_USER >> app.yaml
- npm install
- npm run build
install:
- gcloud config set compute/zone us-east1-b
- gcloud config set project scs-shadow
script:
- gcloud -q app deploy app.yaml
